/**
 * `MANUAL.html`, written from the same data as the screen's help (guide.ts,
 * keymap.ts) — so the manual says what the tool card says, with the same keys.
 * `scripts/build-manual.ts` writes the file (`npm run manual`); it is not
 * committed, so generate it when you want to read or share it.
 *
 * Pure string building, no DOM: it runs under Node.
 */
import {
  GLOSSARY,
  GLOSSARY_CATEGORIES,
  LEFT_SECTIONS,
  MODIFIER_HELP,
  TAB_LABELS,
  TAB_SECTIONS,
  TOOL_TAB,
  TOPICS,
  fillKeys,
  topicKey,
  type Section,
  type TabId,
  type Topic,
} from "./guide.ts";
import { shortcutRows } from "./shortcut-rows.ts";

const esc = (s: string): string => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
const text = (s: string): string => esc(fillKeys(s));

function topic(id: string, t: Topic): string {
  const key = topicKey(t);
  return `<article class="topic" id="${id}">
<h3>${esc(t.name)} <small>${esc(t.ja)}</small>${key ? ` <kbd>${esc(key)}</kbd>` : ""}</h3>
<p>${text(t.one)}</p>
<h4>使い方</h4>
<ol>${t.steps.map((s) => `<li>${text(s)}</li>`).join("")}</ol>
<h4>こんな時に</h4>
<ul>${t.uses.map((s) => `<li>${text(s)}</li>`).join("")}</ul>
</article>`;
}

const sections = (list: readonly Section[]): string =>
  `<dl class="sections">${list.map((s) => `<dt>${esc(s.title)}</dt><dd>${text(s.desc)}</dd>`).join("")}</dl>`;

/** The whole manual as one HTML document. */
export function renderManual(): string {
  const tools = (Object.keys(TOOL_TAB) as (keyof typeof TOOL_TAB)[]).map((id) => topic(id, TOPICS[id])).join("\n");
  // Each tab's sections, after its own topic when the tab is not a tool's
  // (a tool's topic is already under ツール).
  const toolTabs = new Set<string>(Object.values(TOOL_TAB));
  const tabs = (Object.keys(TAB_LABELS) as TabId[])
    .map((tab) => {
      const own = toolTabs.has(tab) ? "" : topic("topic-" + tab, TOPICS[tab as Exclude<TabId, "xform">]);
      return `<section id="tab-${tab}">\n<h3>${esc(TAB_LABELS[tab])}</h3>\n${own}\n${sections(TAB_SECTIONS[tab])}\n</section>`;
    })
    .join("\n");
  const mods = `<table><tbody>${Object.values(MODIFIER_HELP)
    .map((m) => `<tr><th>${esc(m.name)}</th><td>${text(m.one)}</td></tr>`)
    .join("")}</tbody></table>`;
  const keys = (["object", "edit"] as const)
    .map(
      (ctx) =>
        `<table><caption>${ctx === "object" ? "Object Mode ／ 共通" : "Edit Mode（Tab で入る）"}</caption><tbody>${shortcutRows(ctx)
          .map((r) => `<tr><td><kbd>${esc(r.keys)}</kbd></td><td>${esc(r.text)}</td></tr>`)
          .join("")}</tbody></table>`,
    )
    .join("\n");
  const glossary = GLOSSARY_CATEGORIES.map(
    (cat) =>
      `<h3>${esc(cat)}</h3><dl class="glossary">${GLOSSARY.filter((g) => g.cat === cat)
        .map((g) => `<dt>${esc(g.en)} <small>${esc(g.ja)}</small></dt><dd>${text(g.desc)}</dd>`)
        .join("")}</dl>`,
  ).join("\n");

  return `<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FORGE 3D マニュアル</title>
<!-- Generated by scripts/build-manual.ts from src/app/guide/ — do not edit by hand. -->
<style>
:root{--bg:#101116;--bg2:#181922;--bd:#2c2d3a;--t1:#e9e9f0;--t2:#a8a9b8;--t3:#7a7b8b;--ac:#8aa6e2;}
body{background:var(--bg);color:var(--t1);font-family:'Hiragino Sans','Zen Kaku Gothic New',sans-serif;line-height:1.7;margin:0;padding:24px 16px;}
main{max-width:860px;margin:0 auto;}
h1{font-size:22px;}h2{font-size:18px;border-bottom:1px solid var(--bd);padding-bottom:6px;margin-top:36px;}
h3{font-size:15px;margin:22px 0 6px;}h4{font-size:11px;color:var(--t3);letter-spacing:1px;margin:8px 0 2px;}
small{color:var(--t3);font-weight:400;margin-left:6px;}
kbd{font-family:ui-monospace,monospace;font-size:12px;border:1px solid var(--bd);border-radius:4px;padding:0 5px;color:var(--ac);}
p,li,dd,td{color:var(--t2);font-size:14px;}
.topic{background:var(--bg2);border:1px solid var(--bd);border-radius:8px;padding:4px 16px 10px;margin:12px 0;}
dt{font-weight:700;margin-top:10px;}dd{margin:2px 0 0 0;}
table{border-collapse:collapse;width:100%;margin:8px 0 16px;}
th,td{border-bottom:1px solid var(--bd);padding:6px 8px;text-align:left;vertical-align:top;}
th{white-space:nowrap;}caption{text-align:left;color:var(--t3);font-size:12px;padding:4px 0;}
nav a{color:var(--ac);margin-right:12px;}
</style>
</head>
<body>
<main>
<h1>FORGE 3D マニュアル</h1>
<p>ブラウザで動く 3D モデリングツール。キー操作は Blender と同じです。画面の「?」から同じ説明と用語集が開けます。</p>
<nav><a href="#tools">ツール</a><a href="#left">左パネル</a><a href="#tabs">右パネル</a><a href="#modifiers">モディファイア</a><a href="#keys">ショートカット</a><a href="#glossary">用語集</a></nav>

<h2 id="tools">ツール</h2>
${tools}

<h2 id="left">左パネル</h2>
${sections(LEFT_SECTIONS)}

<h2 id="tabs">右パネル（タブ）</h2>
${tabs}

<h2 id="modifiers">モディファイア</h2>
<p>元の形を残したまま加工を重ねがけします。上から順にかかり、Apply で確定します。</p>
${mods}

<h2 id="keys">ショートカット</h2>
<p>キーは Blender と同じです。</p>
${keys}

<h2 id="glossary">用語集</h2>
${glossary}
</main>
</body>
</html>
`;
}
